version: '3.7'
services:
  web:
    # Where find Dockerfile
    build: .
    volumes:
      - ./trading_platform/:/app/trading_platform
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev